name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y gcc pkg-config libbtrfs-dev libdevmapper-dev libgpgme-dev lvm2 make

    - name: Build
      run: make build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # See both:
    # https://github.com/actions/runner-images/issues/9425
    # https://noobient.com/2023/11/15/fixing-ubuntu-containers-failing-to-start-with-systemd/
    - name: Setup podman and patch crun
      env:
        CRUN_VER: 1.14.4
      run: |
        sudo apt-get install -y podman
        echo -e "Replacing $(crun --version | head -1) with newer (${CRUN_VER})"
        curl -Lo crun "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64"
        sudo install crun /usr/bin/crun

    - name: Install test dependencies
      run: |
        curl -s https://raw.githubusercontent.com/89luca89/distrobox/1.7.1/install | sudo sh
        ./utils/create_test_env.sh

    - name: Test
      run: |
        distrobox enter -r albius_test -- sudo make test
