name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install build dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libbtrfs-dev libdevmapper-dev libgpgme-dev lvm2 parted

    - name: Build
      run: go build -v ./...

    - name: Test
      run: sudo go test -v ./...
