name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y gcc pkg-config libbtrfs-dev libdevmapper-dev libgpgme-dev lvm2 make

    - name: Build
      run: make build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      # https://noobient.com/2023/11/15/fixing-ubuntu-containers-failing-to-start-with-systemd/
    - name: Setup podman
      run: |
        echo -e "Replacing $(crun --version | head -1) with newer"
        sudo apt-get install -y podman
        sudo CRUN_VER='1.11.2' curl -L "https://github.com/containers/crun/releases/download/${CRUN_VER}/crun-${CRUN_VER}-linux-amd64" -o "/usr/bin/crun"
        sudo chmod +x "/usr/bin/crun"

    - name: Install test dependencies
      run: |
        curl -s https://raw.githubusercontent.com/89luca89/distrobox/1.7.1/install | sudo sh
        ./utils/create_test_env.sh

    - name: Test
      run: |
        distrobox enter -r albius_test -- sudo make test
