name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/vanilla-os/pico:main

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Install build dependencies
      run: |
          apt-get update
          apt-get install -y gcc pkg-config libbtrfs-dev libdevmapper-dev libgpgme-dev lvm2

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install test dependencies
      run: |
        curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
        ./utils/create_test_env.sh

    - name: Test
      run: |
        distrobox enter -r albius_test -- sudo go test -v ./...

  deb-build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: apt update && apt install dpkg-dev build-essential debhelper libbtrfs-dev libdevmapper-dev libgpgme-dev lvm2 dh-golang golang-go gcc pkg-config  -y

    - name: Build debian package
      run: |
        dpkg-buildpackage --no-sign
        mv ../*.deb ../albius.deb

    - uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          /__w/vanilla-installer/albius.deb
